services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/japanese-memory.com:/etc/letsencrypt/live/japanese-memory.com:ro
      - /etc/letsencrypt/archive/japanese-memory.com:/etc/letsencrypt/archive/japanese-memory.com:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    depends_on:
      - next-app
